name: Test

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment, 'dev' or 'prod'."
        required: true

jobs:
  deploy:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: test
        env:
          BUCKET: ${{github.event.inputs.env == 'prod' && 'operations' || '$github.event.inputs.env'}}
        run: echo "$BUCKET"
